import type { IconType } from "react-icons";
import {
  SiC, SiCplusplus, SiPython, SiSharp, SiJavascript, SiTypescript, SiPhp, SiRuby, SiGo, SiRust,
  SiKotlin, SiSwift, SiDart, SiScala, SiR, SiPerl, SiLua, SiHaskell, SiElixir, SiClojure,
  SiHtml5, SiCss, SiTailwindcss, SiBootstrap, SiSass, SiReact, SiAngular, SiVuedotjs, SiSvelte,
  SiNextdotjs, SiNuxt, SiRedux, SiJquery, SiWebpack, SiVite, SiThreedotjs, SiGreensock,
  SiNodedotjs, SiExpress, SiDjango, SiFlask, SiSpringboot, SiDotnet, SiLaravel, SiRubyonrails,
  SiFastapi, SiNestjs, SiGraphql, SiApollographql, SiSocketdotio, SiNginx, SiApache,
  SiMysql, SiPostgresql, SiMongodb, SiSqlite, SiRedis, SiFirebase, SiSupabase,
  SiElasticsearch, SiApachecassandra, SiPrisma, SiSequelize,
  SiGit, SiGithub, SiGitlab, SiBitbucket, SiDocker, SiKubernetes, SiJenkins, SiTerraform,
  SiAnsible, SiVercel, SiNetlify, SiPostman, SiJira, SiConfluence, SiFigma,
  SiLinux, SiUbuntu, SiDebian, SiCentos, SiRedhat, SiApple, SiAndroid,
  SiGooglecloud, SiCloudflare, SiDigitalocean,
  SiNumpy, SiPandas, SiScikitlearn, SiTensorflow, SiPytorch, SiKeras, SiJupyter, SiOpencv,
  SiApachespark, SiApachehadoop, SiApachekafka, SiGrafana, SiPrometheus,
  SiUnity, SiUnrealengine, SiBlender, SiArduino, SiRaspberrypi, SiEspressif,
  SiFlutter, SiIonic, SiAndroidstudio, SiXcode, SiIntellijidea, SiEclipseide,
  SiWordpress, SiShopify, SiDrupal, SiJoomla, SiWebflow,
  SiHuggingface, SiLangchain, SiStripe, SiPaypal,
  SiJson, SiYaml, SiMarkdown, SiSwagger, SiOpenapiinitiative,
  SiNpm, SiYarn, SiPnpm, SiEslint, SiPrettier, SiJest, SiCypress, SiSelenium, SiStorybook,
} from "react-icons/si";
import { FaJava, FaCalculator, FaBrain, FaComments, FaUsers, FaFileAlt, FaRobot } from "react-icons/fa";

export type CatalogIcon = {
  name: string;
  label: string;
  Icon: IconType;
};

export const ICON_CATALOG: CatalogIcon[] = [
  { name: "FaJava", label: "Java", Icon: FaJava },
  { name: "FaCalculator", label: "Quantitative Aptitude", Icon: FaCalculator },
  { name: "FaBrain", label: "Logical / Non-Verbal Reasoning", Icon: FaBrain },
  { name: "FaComments", label: "Communication / Verbal", Icon: FaComments },
  { name: "FaUsers", label: "Group Discussion / Interview Prep", Icon: FaUsers },
  { name: "FaFileAlt", label: "Resume Building", Icon: FaFileAlt },
  { name: "FaRobot", label: "Robotics Fundamentals", Icon: FaRobot },
  { name: "SiC", label: "C", Icon: SiC },
  { name: "SiCplusplus", label: "C++", Icon: SiCplusplus },
  { name: "SiPython", label: "Python", Icon: SiPython },
  { name: "SiSharp", label: "C#", Icon: SiSharp },
  { name: "SiJavascript", label: "JavaScript", Icon: SiJavascript },
  { name: "SiTypescript", label: "TypeScript", Icon: SiTypescript },
  { name: "SiPhp", label: "PHP", Icon: SiPhp },
  { name: "SiRuby", label: "Ruby", Icon: SiRuby },
  { name: "SiGo", label: "Go", Icon: SiGo },
  { name: "SiRust", label: "Rust", Icon: SiRust },
  { name: "SiKotlin", label: "Kotlin", Icon: SiKotlin },
  { name: "SiSwift", label: "Swift", Icon: SiSwift },
  { name: "SiDart", label: "Dart", Icon: SiDart },
  { name: "SiScala", label: "Scala", Icon: SiScala },
  { name: "SiR", label: "R", Icon: SiR },
  { name: "SiPerl", label: "Perl", Icon: SiPerl },
  { name: "SiLua", label: "Lua", Icon: SiLua },
  { name: "SiHaskell", label: "Haskell", Icon: SiHaskell },
  { name: "SiElixir", label: "Elixir", Icon: SiElixir },
  { name: "SiClojure", label: "Clojure", Icon: SiClojure },
  { name: "SiHtml5", label: "HTML5", Icon: SiHtml5 },
  { name: "SiCss", label: "CSS3", Icon: SiCss },
  { name: "SiTailwindcss", label: "Tailwind CSS", Icon: SiTailwindcss },
  { name: "SiBootstrap", label: "Bootstrap", Icon: SiBootstrap },
  { name: "SiSass", label: "Sass", Icon: SiSass },
  { name: "SiReact", label: "React", Icon: SiReact },
  { name: "SiAngular", label: "Angular", Icon: SiAngular },
  { name: "SiVuedotjs", label: "Vue.js", Icon: SiVuedotjs },
  { name: "SiSvelte", label: "Svelte", Icon: SiSvelte },
  { name: "SiNextdotjs", label: "Next.js", Icon: SiNextdotjs },
  { name: "SiNuxt", label: "Nuxt.js", Icon: SiNuxt },
  { name: "SiRedux", label: "Redux", Icon: SiRedux },
  { name: "SiJquery", label: "jQuery", Icon: SiJquery },
  { name: "SiWebpack", label: "Webpack", Icon: SiWebpack },
  { name: "SiVite", label: "Vite", Icon: SiVite },
  { name: "SiThreedotjs", label: "Three.js", Icon: SiThreedotjs },
  { name: "SiGreensock", label: "GSAP", Icon: SiGreensock },
  { name: "SiNodedotjs", label: "Node.js", Icon: SiNodedotjs },
  { name: "SiExpress", label: "Express", Icon: SiExpress },
  { name: "SiDjango", label: "Django", Icon: SiDjango },
  { name: "SiFlask", label: "Flask", Icon: SiFlask },
  { name: "SiSpringboot", label: "Spring Boot", Icon: SiSpringboot },
  { name: "SiDotnet", label: ".NET", Icon: SiDotnet },
  { name: "SiLaravel", label: "Laravel", Icon: SiLaravel },
  { name: "SiRubyonrails", label: "Ruby on Rails", Icon: SiRubyonrails },
  { name: "SiFastapi", label: "FastAPI", Icon: SiFastapi },
  { name: "SiNestjs", label: "NestJS", Icon: SiNestjs },
  { name: "SiGraphql", label: "GraphQL", Icon: SiGraphql },
  { name: "SiApollographql", label: "Apollo GraphQL", Icon: SiApollographql },
  { name: "SiSocketdotio", label: "Socket.IO", Icon: SiSocketdotio },
  { name: "SiNginx", label: "Nginx", Icon: SiNginx },
  { name: "SiApache", label: "Apache", Icon: SiApache },
  { name: "SiMysql", label: "MySQL", Icon: SiMysql },
  { name: "SiPostgresql", label: "PostgreSQL", Icon: SiPostgresql },
  { name: "SiMongodb", label: "MongoDB", Icon: SiMongodb },
  { name: "SiSqlite", label: "SQLite", Icon: SiSqlite },
  { name: "SiRedis", label: "Redis", Icon: SiRedis },
  { name: "SiFirebase", label: "Firebase", Icon: SiFirebase },
  { name: "SiSupabase", label: "Supabase", Icon: SiSupabase },
  { name: "SiElasticsearch", label: "Elasticsearch", Icon: SiElasticsearch },
  { name: "SiApachecassandra", label: "Cassandra", Icon: SiApachecassandra },
  { name: "SiPrisma", label: "Prisma", Icon: SiPrisma },
  { name: "SiSequelize", label: "Sequelize", Icon: SiSequelize },
  { name: "SiGit", label: "Git", Icon: SiGit },
  { name: "SiGithub", label: "GitHub", Icon: SiGithub },
  { name: "SiGitlab", label: "GitLab", Icon: SiGitlab },
  { name: "SiBitbucket", label: "Bitbucket", Icon: SiBitbucket },
  { name: "SiDocker", label: "Docker", Icon: SiDocker },
  { name: "SiKubernetes", label: "Kubernetes", Icon: SiKubernetes },
  { name: "SiJenkins", label: "Jenkins", Icon: SiJenkins },
  { name: "SiTerraform", label: "Terraform", Icon: SiTerraform },
  { name: "SiAnsible", label: "Ansible", Icon: SiAnsible },
  { name: "SiVercel", label: "Vercel", Icon: SiVercel },
  { name: "SiNetlify", label: "Netlify", Icon: SiNetlify },
  { name: "SiPostman", label: "Postman", Icon: SiPostman },
  { name: "SiJira", label: "Jira", Icon: SiJira },
  { name: "SiConfluence", label: "Confluence", Icon: SiConfluence },
  { name: "SiFigma", label: "Figma", Icon: SiFigma },
  { name: "SiLinux", label: "Linux", Icon: SiLinux },
  { name: "SiUbuntu", label: "Ubuntu", Icon: SiUbuntu },
  { name: "SiDebian", label: "Debian", Icon: SiDebian },
  { name: "SiCentos", label: "CentOS", Icon: SiCentos },
  { name: "SiRedhat", label: "Red Hat", Icon: SiRedhat },
  { name: "SiApple", label: "Apple / macOS", Icon: SiApple },
  { name: "SiAndroid", label: "Android", Icon: SiAndroid },
  { name: "SiGooglecloud", label: "Google Cloud", Icon: SiGooglecloud },
  { name: "SiCloudflare", label: "Cloudflare", Icon: SiCloudflare },
  { name: "SiDigitalocean", label: "DigitalOcean", Icon: SiDigitalocean },
  { name: "SiNumpy", label: "NumPy", Icon: SiNumpy },
  { name: "SiPandas", label: "Pandas", Icon: SiPandas },
  { name: "SiScikitlearn", label: "scikit-learn", Icon: SiScikitlearn },
  { name: "SiTensorflow", label: "TensorFlow", Icon: SiTensorflow },
  { name: "SiPytorch", label: "PyTorch", Icon: SiPytorch },
  { name: "SiKeras", label: "Keras", Icon: SiKeras },
  { name: "SiJupyter", label: "Jupyter", Icon: SiJupyter },
  { name: "SiOpencv", label: "OpenCV", Icon: SiOpencv },
  { name: "SiApachespark", label: "Apache Spark", Icon: SiApachespark },
  { name: "SiApachehadoop", label: "Hadoop", Icon: SiApachehadoop },
  { name: "SiApachekafka", label: "Kafka", Icon: SiApachekafka },
  { name: "SiGrafana", label: "Grafana", Icon: SiGrafana },
  { name: "SiPrometheus", label: "Prometheus", Icon: SiPrometheus },
  { name: "SiUnity", label: "Unity", Icon: SiUnity },
  { name: "SiUnrealengine", label: "Unreal Engine", Icon: SiUnrealengine },
  { name: "SiBlender", label: "Blender", Icon: SiBlender },
  { name: "SiArduino", label: "Arduino", Icon: SiArduino },
  { name: "SiRaspberrypi", label: "Raspberry Pi", Icon: SiRaspberrypi },
  { name: "SiEspressif", label: "ESP32 / Espressif", Icon: SiEspressif },
  { name: "SiFlutter", label: "Flutter", Icon: SiFlutter },
  { name: "SiIonic", label: "Ionic", Icon: SiIonic },
  { name: "SiAndroidstudio", label: "Android Studio", Icon: SiAndroidstudio },
  { name: "SiXcode", label: "Xcode", Icon: SiXcode },
  { name: "SiIntellijidea", label: "IntelliJ IDEA", Icon: SiIntellijidea },
  { name: "SiEclipseide", label: "Eclipse", Icon: SiEclipseide },
  { name: "SiWordpress", label: "WordPress", Icon: SiWordpress },
  { name: "SiShopify", label: "Shopify", Icon: SiShopify },
  { name: "SiDrupal", label: "Drupal", Icon: SiDrupal },
  { name: "SiJoomla", label: "Joomla", Icon: SiJoomla },
  { name: "SiWebflow", label: "Webflow", Icon: SiWebflow },
  { name: "SiHuggingface", label: "Hugging Face", Icon: SiHuggingface },
  { name: "SiLangchain", label: "LangChain", Icon: SiLangchain },
  { name: "SiStripe", label: "Stripe", Icon: SiStripe },
  { name: "SiPaypal", label: "PayPal", Icon: SiPaypal },
  { name: "SiJson", label: "JSON", Icon: SiJson },
  { name: "SiYaml", label: "YAML", Icon: SiYaml },
  { name: "SiMarkdown", label: "Markdown", Icon: SiMarkdown },
  { name: "SiSwagger", label: "Swagger", Icon: SiSwagger },
  { name: "SiOpenapiinitiative", label: "OpenAPI", Icon: SiOpenapiinitiative },
  { name: "SiNpm", label: "npm", Icon: SiNpm },
  { name: "SiYarn", label: "Yarn", Icon: SiYarn },
  { name: "SiPnpm", label: "pnpm", Icon: SiPnpm },
  { name: "SiEslint", label: "ESLint", Icon: SiEslint },
  { name: "SiPrettier", label: "Prettier", Icon: SiPrettier },
  { name: "SiJest", label: "Jest", Icon: SiJest },
  { name: "SiCypress", label: "Cypress", Icon: SiCypress },
  { name: "SiSelenium", label: "Selenium", Icon: SiSelenium },
  { name: "SiStorybook", label: "Storybook", Icon: SiStorybook },
];

export function getIconByName(name: string): IconType | undefined {
  return ICON_CATALOG.find((i) => i.name === name)?.Icon;
}
